name: ironrodchat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  table_calendar: ^3.0.9
  animated_background: ^2.0.0
  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.8
  firebase_database: ^10.4.0
  country_flags: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/sounds/send.mp3
    - assets/sounds/receive.mp3
    - assets/images/flags/br.png
